default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: rails_problem1_development
test:
  <<: *default
  database: rails_problem1_test
production:
  <<: *default
  database: rails_problem1_production
  username: rails_problem1
  password: <%= ENV['RAILS_PROBLEM1_DATABASE_PASSWORD'] %>
